print("What is your name?")
name = input()
print("How old are you? (years) ", end=' ')
age = input()
print("How tall are you? (x\'y\")", end=' ')
height = input ()
print("How much do you weigh?", end=' ')
weight = input()

print(f"so, you're {age} years old, {height} tall, and {weight} lbs and you go by {name}")